### ISSUE TITLE
[FEATURE] Do not hide CVC field

### ISSUE THREAD

**Issue by DagAgren** [verygoodsecurity/vgs-collect-ios#151]
It would be nice if having the CVC field be a masked password field would be optional. This does not really seem like it adds any useful security, and it makes it harder for the user to verify that the data they have entered is incorrect. We are replacing our existing credit card addition screen with one using VGS, and our old one did not mask the CVC field, and we would like to keep it that way.

**Comment by dmytrokhl** [comment]
Hello @DagAgren, 

this is available since [v1.5.2](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.5.2). You can set masked field like `cvcTextField.isSecureTextEntry = false`. 

Note that mask actually provide additional security - in case user or application make screenshots or record the application screen, masked field will be empty on screenshot. Also it's not allowed to copy data from secured fields.

**Comment by dmytrokhl** [comment]
Closed, since the feature released in [v1.5.2](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.5.2).
