### ISSUE TITLE
[FEATURE] Accessibility support for text fields

### ISSUE THREAD

**Issue by isuert** [verygoodsecurity/vgs-collect-ios#300]
**Is your feature request related to a problem? Please describe.**
Currently, it does not seem possible to provide accessibility attributes (like `accessibilityLabel`, `accessibilityHint` etc.) to the underlying text field that [VGSTextField](https://verygoodsecurity.github.io/vgs-collect-ios/Classes/VGSTextField.html) contains. We can only add such attributes to `VGSTextField` itself.

**Describe the solution you'd like**
Possibility to pass accessibility attributes to the underlying text field that `VGSTextField` contains.

**Possible solution**
Similar to what's already in place for [placeholder](https://verygoodsecurity.github.io/vgs-collect-ios/Classes/VGSTextField.html#/s:13VGSCollectSDK12VGSTextFieldC11placeholderSSSgvp) attribute, you can expose extra attributes for accessibility which would be passed to the underlying text field. While doing so, would be nice if it's still possible to add accessibility attributes to VGSTextField itself. For this, you might consider using prefixed names for such attributes, for example, `textFieldAccessibilityLabel` - in this case, `accessibilityLabel` can still be used to control the accessibility of `VGSTextField`.

**Comment by EugeneIOs** [comment]
Hi, @isuert. 
we will look into this feature, yes, some additional wrappers for `VGSTextField` are required to do this.

**Comment by EugeneIOs** [comment]
@isuert 
Hello, we checked current accessibility options. 
As we have wrapper for `UITextField` adding `accessibilityLabel` for `VGSTextField` won't work unless `VGSTextField` property `isAccessibilityElement` set to `true`. Default is `false` since `VGSTextField` is just a `UIView`.

We can add `accessibilityLabel` and `accessibilityHint` options to set them directly into the underlying `textField`.
Are there any other accessibility options you need? 
Since `UITextField` is native iOS control it has its own default `accessibility` properties and features working out of the box.

**Comment by isuert** [comment]
> We can add `accessibilityLabel` and `accessibilityHint` options to set them directly into the underlying `textField`. Are there any other accessibility options you need?

That would work for my use case! Thanks!
I'm not sure what other attributes might be necessary for covering more cases, but this sounds like a good start. 🙌

**Comment by EugeneIOs** [comment]
@isuert.
Thank you for feedback, we can add these two options for the underlying textField.

**Comment by EugeneIOs** [comment]
@isuert 
Please check release [1.9.4](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.9.4) with `textFieldAccessibilityLabel` and `textFieldAccessibilityHint` options.

**Comment by isuert** [comment]
Thanks a lot! 🙌
